### ISSUE TITLE
{% extends "evaluation.prompty" %} Return errors template not found

### ISSUE THREAD

**Issue by Skyquek** [microsoft/prompty#153]
When I run this file https://github.com/microsoft/prompty/blob/951f44a5d7857b344c585640a9e3197f5f1476fd/runtime/prompty/tests/prompts/faithfulness.prompty#L16

It seems like template is missing. How can I fix it?

```cmd
Call Stack: Template render error: (unknown path)
  Template render error: (unknown path)
  Error: template not found: evaluation.prompty
	at Object._prettifyError (c:\Users\alex\.vscode\extensions\ms-toolsai.prompty-0.1.2024060511\packages\core\out\extension.js:3624:15)
	at c:\Users\alex\.vscode\extensions\ms-toolsai.prompty-0.1.2024060511\packages\core\out\extension.js:13969:24
	at Template2.root [as rootRenderFunc] (eval at _compile (c:\Users\alex\.vscode\extensions\ms-toolsai.prompty-0.1.2024060511\packages\core\out\extension.js:14027:22), <anonymous>:39:3)
	at Template2.render2 [as render] (c:\Users\alex\.vscode\extensions\ms-toolsai.prompty-0.1.2024060511\packages\core\out\extension.js:13964:14)
	at Environment2.renderString (c:\Users\alex\.vscode\extensions\ms-toolsai.prompty-0.1.2024060511\packages\core\out\extension.js:13835:21)
	at Object.renderString (c:\Users\alex\.vscode\extensions\ms-toolsai.prompty-0.1.2024060511\packages\core\out\extension.js:14529:19)
	at NunjucksRenderer.invokeSync (c:\Users\alex\.vscode\extensions\ms-toolsai.prompty-0.1.2024060511\packages\core\out\extension.js:18102:25)
	at NunjucksRenderer.invoke (c:\Users\alex\.vscode\extensions\ms-toolsai.prompty-0.1.2024060511\packages\core\out\extension.js:18099:37)
	at NunjucksRenderer.call (c:\Users\alex\.vscode\extensions\ms-toolsai.prompty-0.1.2024060511\packages\core\out\extension.js:17948:27)
	at _InvokerFactory.call (c:\Users\alex\.vscode\extensions\ms-toolsai.prompty-0.1.2024060511\packages\core\out\extension.js:17991:56)
	at _Prompty.prepare (c:\Users\alex\.vscode\extensions\ms-toolsai.prompty-0.1.2024060511\packages\core\out\extension.js:18182:35)
	at execute (c:\Users\alex\.vscode\extensions\ms-toolsai.prompty-0.1.2024060511\packages\core\out\extension.js:93079:47)
	at c:\Users\alex\.vscode\extensions\ms-toolsai.prompty-0.1.2024060511\packages\core\out\extension.js:93825:34
	at J_.d (file:///c:/Users/alex/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:32324)
	at J_.withProgress (file:///c:/Users/alex/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:32190)
	at Object.withProgress (file:///c:/Users/alex/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:157:47957)
	at runPrompt (c:\Users\alex\.vscode\extensions\ms-toolsai.prompty-0.1.2024060511\packages\core\out\extension.js:93769:20)
	at cw.h (file:///c:/Users/alex/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:32833)
	at cw.$executeContributedCommand (file:///c:/Users/alex/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:33683)
	at Dy.S (file:///c:/Users/alex/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:115275)
	at Dy.Q (file:///c:/Users/alex/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:115055)
	at Dy.M (file:///c:/Users/alex/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:114144)
	at Dy.L (file:///c:/Users/alex/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:113249)
	at kh.value (file:///c:/Users/alex/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:112046)
	at P.B (file:///c:/Users/alex/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
	at P.fire (file:///c:/Users/alex/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:964)
	at Vn.fire (file:///c:/Users/alex/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:9457)
	at kh.value (file:///c:/Users/alex/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:13296)
	at P.B (file:///c:/Users/alex/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
	at P.fire (file:///c:/Users/alex/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:964)
	at Vn.fire (file:///c:/Users/alex/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:9457)
	at MessagePortMain.<anonymous> (file:///c:/Users/alex/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:11588)
	at MessagePortMain.emit (node:events:518:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949)
```

**Comment by Skyquek** [comment]
![Image](https://github.com/user-attachments/assets/8fa05e16-57e3-4dab-ac54-af617374ef3d)

Also the property base is not allowed.

**Comment by sethjuarez** [comment]
Yes - this is an experimental feature that works in the python runtime but not the JavaScript runtime (which the extension uses). I am working on updating the extension to handle these cases.

**Comment by Skyquek** [comment]
@sethjuarez in our use case, we would be also using this in C# semantic kernel, hope that the fix can cater for C# based semantic kernel as well. Thanks in advance.😁
